package:
  name: cups-libs-cos7-ppc64le
  version: 1.6.3

source:
  - url: http://mirror.centos.org/altarch/7/os/ppc64le/Packages/cups-libs-1.6.3-43.el7.ppc64le.rpm
    sha256: 1c30378e2926ee49b4520d24ab9e727187850f6d0202dbd4e123681f593f2648 
    no_hoist: true
    folder: binary
  - url: http://vault.centos.org/centos/7.7.1908/os/Source/SPackages/cups-1.6.3-43.el7.src.rpm
    folder: source

build:
  number: 2
  noarch: generic
  missing_dso_whitelist:
    - '*'



about:
  home: http://www.cups.org/
  license: LGPLv2
  license_family: LGPL
  summary: "(CDT) Common Unix Printing System - libraries"
  description: |
        The Common UNIX Printing System provides a portable printing layer for UNIX®
        operating systems. It has been developed by Easy Software Products to promote
        a standard printing solution for all UNIX vendors and users. CUPS provides the
        System V and Berkeley command-line interfaces. The cups-libs package provides
        libraries used by applications to use CUPS natively, without needing the
        lp/lpr commands.
