{% set version = "5.14.1" %}

package:
  name: pyqt
  version: {{ version }}


requirements:
  run:
    - pyqt5
    - pyqtwebengine



about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: Commercial, GPL-2.0, GPL-3.0
  license_family: GPL
  summary: 'Python binding of the cross-platform GUI toolkit Qt.'
  description: |
    "PyQt is a set of Python v2 and v3 bindings for The Qt Company's Qt
    application framework and runs on all platforms supported by Qt including
    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and
    will build against Qt v5. The bindings are implemented as a set of Python
    modules and contain over 1,000 classes."
  doc_url: https://www.riverbankcomputing.com/software/pyqt/
  dev_url: https://github.com/pyqt


