# A few variables that make this a tiny bit more portable
{% set centos_name = "xcb-util" %}
{% set name = centos_name |lower %}
{% set version = '0.4.0' %}
{% set centos_build = '2' %}
# No good way to get this other than to fail once, I think???
{% set so_version = '1' %}
{% set el = 'el7' %}
{% set arch = "ppc64le" %}
{% set sysroot_arch = "powerpc64le" %}
{% set cos = "cos7" %}
{% set url_base = "http://mirror.centos.org/altarch/7/os/ppc64le/Packages/" %}

package:
  name: {{ name }}-{{ cos }}-{{ arch }}
  version: {{ version }}

source:
  - url: {{ url_base }}{{ centos_name }}-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: 306b9c82a841d1b9f215422733fca41ca3fd71edf446fbaa961c2a2c9dc7d223
    # conda seems to remove folders if they are the only ones there
    # we need to keep the structure of the RPM
    # https://github.com/conda/conda-build/issues/3595
    folder: binary/usr
  - url: {{ url_base }}{{ centos_name }}-devel-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: 35b0809dde97a0f2674d45dc04c3b40039fb9ca3ee1749755e348c334fd56c7f
    folder: devel/usr

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

test:
  # dummy requirement to workaround a bug with the CDT tests
  requires:
    - zlib
  commands:
    - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/lib{{ centos_name }}.so.{{ so_version }}"

outputs:
  - name: {{ name }}-{{ cos }}-{{ arch }}
    build:
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/binary/* .

  - name: {{ name }}-devel-{{ cos }}-{{ arch }}
    build:
      noarch: generic
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/devel/* .
    requirements:
      - {{ pin_subpackage(name + '-' + cos + '-' + arch, exact=True) }}
    test:
      # dummy requirement to workaround a bug with the CDT tests
      requires:
        - zlib
      commands:
        - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/lib{{ centos_name }}.so"

about:
  home: https://dri.sourceforge.net
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "(CDT) Direct Rendering Manager runtime library"
  description: Direct Rendering Manager runtime library

extra:
  recipe-maintainers:
    - jayfurmanek

