# A few variables that make this a tiny bit more portable
{% set centos_name = "libsepol" %}
{% set name = centos_name |lower %}
{% set version = '2.5' %}
{% set centos_build = '10' %}
# No good way to get this other than to fail once, I think???
{% set so_version = '1' %}
{% set el = 'el7' %}
{% set arch = "ppc64le" %}
{% set sysroot_arch = "powerpc64le" %}
{% set cos = "cos7" %}
{% set url_base = "http://mirror.centos.org/altarch/7/os/ppc64le/Packages/" %}

package:
  name: {{ name }}-{{ cos }}-{{ arch }}
  version: {{ version }}

source:
  - url: {{ url_base }}{{ centos_name }}-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: f3578f4b8b1659ffbc76148cec3db6edc7efc28b1e6bcdb9a2a9845201ce27d9
    # conda seems to remove folders if they are the only ones there
    # we need to keep the structure of the RPM
    # https://github.com/conda/conda-build/issues/3595
    folder: binary/usr
  - url: {{ url_base }}{{ centos_name }}-devel-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: f93d653d716719b2bb5952b55ab5f9295d8ec046867ffcb0ec30ebe5870d1b08
    folder: devel/usr

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

test:
  # dummy requirement to workaround a bug with the CDT tests
  requires:
    - zlib
  commands:
    - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/{{ centos_name }}.so.{{ so_version }}"

outputs:
  - name: {{ name }}-{{ cos }}-{{ arch }}
    build:
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/binary/* .

  - name: {{ name }}-devel-{{ cos }}-{{ arch }}
    build:
      noarch: generic
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/devel/* .
    requirements:
      - {{ pin_subpackage(name + '-' + cos + '-' + arch, exact=True) }}
    test:
      # dummy requirement to workaround a bug with the CDT tests
      requires:
        - zlib
      commands:
        - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/{{ centos_name }}.so"

about:
  home: https://github.com/SELinuxProject/selinux/wiki
  license: LGPL (>= 2)
  license_family: LGPL
  license_file: COPYING
  summary: "The libsepol-devel package contains the libraries and header files needed for developing applications that manipulate binary policies."
  description: The libsepol-devel package contains the libraries and header files needed for developing applications that manipulate binary policies.

extra:
  recipe-maintainers:
    - regiscely
