# A few variables that make this a tiny bit more portable
{% set centos_name = "mesa-libgbm" %}
{% set lib_name = "libgbm" %}
{% set name = centos_name |lower %}
{% set version = '18.3.4' %}
{% set centos_build = '5' %}
# No good way to get this other than to fail once, I think???
{% set so_version = '1' %}
{% set el = 'el7' %}
{% set arch = "ppc64le" %}
{% set sysroot_arch = "powerpc64le" %}
{% set cos = "cos7" %}
{% set url_base = "http://mirror.centos.org/altarch/7/os/ppc64le/Packages/" %}


package:
  name: {{ name }}-{{ cos }}-{{ arch }}
  version: {{ version }}

source:
  - url: {{ url_base }}{{ centos_name }}-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: ccf0a95f0db1536099de969930fc9ae248da3527a2da26bd452a504517a17086
    # conda seems to remove folders if they are the only ones there
    # we need to keep the structure of the RPM
    # https://github.com/conda/conda-build/issues/3595
    folder: binary/usr
  - url: {{ url_base }}{{ centos_name }}-devel-{{ version }}-{{ centos_build }}.{{ el }}.{{ arch }}.rpm
    sha256: 481ae8f8fb8ddb35139aa262b79640cf8c77124ca8ed69187c4505b09956ff18 
    folder: devel/usr

build:
  number: 0
  noarch: generic
  missing_dso_whitelist:
    - '*'

test:
  # dummy requirement to workaround a bug with the CDT tests
  requires:
    - zlib
  commands:
    - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/{{ lib_name }}.so.{{ so_version }}"

outputs:
  - name: {{ name }}-{{ cos }}-{{ arch }}
    build:
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/binary/* .

  - name: {{ name }}-devel-{{ cos }}-{{ arch }}
    build:
      noarch: generic
      script:
        - mkdir -p {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot
        - pushd {{ PREFIX }}/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot > /dev/null 2>&1
        - cp -Rf {{ SRC_DIR }}/devel/* .
    requirements:
      - {{ pin_subpackage(name + '-' + cos + '-' + arch, exact=True) }}
    test:
      # dummy requirement to workaround a bug with the CDT tests
      requires:
        - zlib
      commands:
        - test -f "$PREFIX/{{ sysroot_arch }}-conda_{{ cos }}-linux-gnu/sysroot/usr/lib64/{{ lib_name }}.so"


about:
  home: http://www.mesa3d.org
  license: MIT
  license_family: MIT
  summary: "(CDT) Mesa gbm library"
  description: |
        Mesa gbm runtime library.

