{% set version = "5.14.1" %}

package:
  name: qt
  version: {{ version }}

source:
  - url: /tmp/qt-everywhere-src-{{ version }}_ppc64le.B.tar.gz
    md5: f294d0105f4606c0e47295c1d63623f0
    patches:
       - patches/0004-qtbase-never-enable-new-dtags.patch
       - patches/0006-qtbase-Do-not-set-PKG_CONFIG_SYSROOT_DIR-when-sysroo.patch

#  - url: http://download.qt.io/community_releases/5.9/5.9.0-final/qtwebkit-opensource-src-5.9.0.tar.xz            # [qtwebkit == 'true']
#    sha256: 8dad193b740055a998312e04a040f2e32a923c0823b2d239b24eab08276a4e04                                      # [qtwebkit == 'true']
#    folder: qtwebkit                                                                                              # [qtwebkit == 'true']
#    patches:                                                                                                      # [qtwebkit == 'true']
#      - patches/0001-qtwebkit-old-ld-compat.patch                                                                         # [qtwebkit == 'true']
#      - patches/0002-qtwebkit-ruby-1.8.patch                                                                              # [qtwebkit == 'true']
#      - patches/0004-qtwebkit-CentOS5-Fix-fucomip-compat-with-gas-2.17.50.patch                                           # [qtwebkit == 'true']
#      - patches/0006-qtwebkit-WTF--StringImpl--copyChars-segfaults-when-built-with-GCC-7.patch                            # [qtwebkit == 'true']


build:
  number: 3
  skip: True  # [win and vc != 14]
  detect_binary_files_with_prefix: true
  # QtWebEngine fails on Linux unless we merge
  merge_build_host: true  # [linux]
  run_exports:
    - {{ pin_subpackage('qt', max_pin='x.x') }}
  missing_dso_whitelist:  # [osx]
    - /usr/lib/libbsm.0.dylib  # [osx]
    - /usr/lib/libcups.2.dylib  # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]
    - /usr/lib/libsandbox.1.dylib  # [osx]
    - '/System/Library/Frameworks/CoreLocation.framework/**'  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11') }}                # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libx11-common') }}         # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-khr-devel') }}        # [linux]
    - {{ cdt('libglvnd') }}              # [linux]
    - {{ cdt('libglvnd-glx') }}          # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxcb-devel') }}          # [linux]
    - {{ cdt('libXdmcp') }}              # [linux]
    - {{ cdt('libXdmcp-devel') }}        # [linux]
    - {{ cdt('libxkbcommon-x11-devel') }}    # [linux]
    - {{ cdt('libxkbcommon-devel') }}    # [linux]
    - {{ cdt('xcb-util') }}              # [linux]
    - {{ cdt('xcb-util-devel') }}        # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi') }}                 # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst') }}               # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('cups-devel') }}            # [linux]

    # For fontconfig + freetype
    - pkg-config                         # [linux]
    - make                               # [unix]
    # Probably only needed for WebEngine
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - m2-gperf                           # [win]
    - m2-bison                           # [win]
    - m2-flex                            # [win]
    - m2-patch                           # [win]
    - jom                                # [win]
    - perl 5.*
    # Add readline here, so that newest readline is used.
    # Otherwise build and host might end up with two different versions
    # If they do, merge_build_host will fail.
    - readline                           # [linux]
  host:
    # For pkg-config gl, fontconfig + freetype
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - gst-plugins-base                   # [linux]
    - gstreamer                          # [linux]
    - glib                               # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    # For WebEngine, but for compatiblity we want to restrict
    # usage of our own libraries. It seems Chromium prefers
    # expat to libxml2 and we will try to froce it to use the
    # bundled one.
    # Other than that (and esp. for Google developed libs) we
    # avoid our own packagess. FFMPEG was not detected anyway,
    # and neither was libvpx (AFAICT).
    # - libxml2                            # [unix]
    # - libxslt                            # [unix]
    # - libopus                            # [unix]
    # - libvpx                             # [unix]
    # - ffmpeg                             # [unix]
    - expat                              # [linux]
    - icu
    - jpeg
    - libpng
    - nspr                               # [unix]
    - nss                                # [unix]
    - sqlite
    - mysql                              # [not win]
    - postgresql                         # [not win]
    - zlib
    - libiconv
    - libxcb                             # [linux]
    # We cannot install OpenSSL into the prefix when building qtwebengine
    # on linux as BoringSSL and OpenSSL then conflict with each other.
    - openssl                            # [win]
    # For QDoc
    # http://doc.qt.io/Qt-5/qdoc-guide-clang.html
    # Only libclang is needed, but needs the full package for detection.
    - llvmdev
    - clangdev
    - libclang
  run:
    - openssl                            # [not osx]
    - libxcb                             # [linux]
    - {{ pin_compatible("nss") }}        # [unix]
    - {{ pin_compatible("nspr") }}       # [unix]
    - {{ pin_compatible("libclang") }}
  run_constrained:                                            # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
  files:
    - test/hello.pro
    - test/main-qtwebengine.cpp
    - test/main.cpp
    - test/main.qml
    - test/qml.qrc
    - test/qrc_qml.cpp
    - test/qtwebengine.pro
    - xcodebuild
    - xcrun
  commands:
    - if not exist %LIBRARY_BIN%\\Qt5WebEngine.dll exit 1                  # [win]
    - test -f $PREFIX/lib/libQt5WebEngine${SHLIB_EXT}                      # [unix]
    # sql plugin
    - test -f $PREFIX/plugins/sqldrivers/libqsqlite${SHLIB_EXT}            # [unix]
    - if not exist %LIBRARY_PREFIX%\plugins\sqldrivers\qsqlite.dll exit 1  # [win]

about:
  home: http://qt-project.org
  license: LGPL-3.0
  license_file: LICENSE.LGPLv3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qtproject

extra:
  recipe-maintainers:
    - ccordoba12
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg

