package:
  name: pyqt5
  version: 5.14.1
source:
  fn:   PyQt5-5.14.1.tar.gz                                                               [unix]
  url:  https://files.pythonhosted.org/packages/3a/fb/eb51731f2dc7c22d8e1a63ba88fb702727b324c6352183a32f27f73b8116/PyQt5-5.14.1.tar.gz    [unix]
  sha1: 51ff3acf3d1271e566807b7132f163cf4cedb848                                          [unix]

  patches:
    - configure.patch       [osx]

requirements:
  build:
    - python
    - pyqt-builder
    - sip     >=5.1

  run:
    - python
    - pyqt5_sip
    - sip     >=5.1

test:
  imports:
    - PyQt5.QtCore

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL

